Updated validity dependencies
NorfairKing/zifter pull request #2
Opened 2018-02-20 16:35 UTC by Nickske666

2018-02-20 16:35 UTC, Nickske666 commented
This is a version bump.

2018-02-21 13:58 UTC, NorfairKing requested changes

2018-02-21 13:58 UTC, NorfairKing commented on zifter/src/Zifter/Zift/Types.hs
> +    validate (ZiftSuccess a) = validate a
This is not semantics preserving. You'll have to take a very close look at the versioun bounds on validity.

2018-02-21 13:58 UTC, NorfairKing commented on zifter/test/Zifter/Zift/Gen.hs
> -    isValid = isValidByValidating
Same comment.

2018-02-21 13:58 UTC, NorfairKing commented on zifter/test/Zifter/Zift/Gen.hs
> +    validate x = isValid (toSRGB24 x) <?@> "Colour"
same comment.

2018-02-21 13:58 UTC, NorfairKing commented on zifter/package.yaml
> +    - genvalidity-path >=0.2 && <0.3
It's better to upgrade the upper bound if necessary, but maintain backward compatibility.

2018-02-21 13:58 UTC, NorfairKing commented on stack.yaml
> +- genvalidity-0.4.0.4
validity is on stackage. Better to wait until the right version is available there.

2018-02-21 13:58 UTC, NorfairKing commented on lts-8.yaml
> +- validity-0.4.0.4
This will probably get us into problems because validity wasn't available yet when this lts was made.

2018-04-24 01:19 UTC, closed without merging